apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
  template:
    metadata:
      labels:
        app: web-deployment 
    spec:
      containers:
        - name: web-app1
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress-service
spec:  
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: web-deployment-service 
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-deployment-service
  labels:
    app: web-deployment
spec:
  type: ClusterIP 
  selector:
    app: web-deployment 
  ports:
    - port: 80
      targetPort: 80
